config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :businesses

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
end

app/models/business.rb
class Business < ActiveRecord::Base
  has_attached_file :image

  validates_attachment :image, presence: true
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates :name,
            :description,
            :email,
            :phone, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.

  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @businesses = Business.all
  end

  def show
    @business = find_business
  end

  def new
    @business = Business.new
  end

  def create
    @business = build_business

    if @business.save
      flash[:notice] = 'Business was successfully created.'
      redirect_to @business
    else
      render :new
    end
  end

  private

    def build_business
      Business.new(business_params)
    end

    def find_business
      Business.find(params[:id])
    end

    def business_params
      params.require(:business).permit(
        :name,
        :description,
        :image,
        :additional_text,
        :email,
        :phone,
        :url,
        :services,
        :slogan
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_flashes.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
   <a class="close" data-dismiss="alert">×</a>
      <%= msg %>
</div>
<% end %>

app/views/businesses/_form.html.erb
<%= render "flashes" -%>
<%= simple_form_for @business, html: { multipart: true } do |f| %>
<ul class="list-group list-group-flush">
  <li class="list-group-item">
    <%= f.file_field :image %>
    <p class="text-muted">
      Ad Image
    </small>


    <%= f.input :name, label: false, placeholder: 'Name' %>
    <p class="text-muted">
      Business Name
    </small>

    <%= f.input :description, label: false, placeholder: 'Description' %>
    <p class="text-muted">
      Address (Kosovo only)
    </small>

    <%= f.input :additional_text, label: false, placeholder: 'Additional Text' %>
    <p class="text-muted">
      1000 characters left
    </small>

    <%= f.input :email, label: false, placeholder: 'E-mail' %>
    <p class="text-muted">
      eg. john.doe@email.com
    </small>

    <%= f.input :phone, label: false, placeholder: 'Phone' %>
    <p class="text-muted">
      Primary Phone Number
    </small>

    <%= f.input :url, label: false, placeholder: 'Website' %>
    <p class="text-muted">
      eg. www.example.com
    </small>

    <%= f.input :services, label: false, placeholder: 'Services' %>
    <p class="text-muted">
      Services list
    </small>

    <%= f.input :slogan, label: false, placeholder: 'Slogan' %>
    <p class="text-muted">
      Business slogan
    </small>
  </li>
  <li class="list-group-item">
    <div class="card-block">
      <%= f.button :submit, class: 'btn-primary card-link' %>
      <a href="#" class="card-link">Another link</a>
    </div>
  </li>
</ul>
<% end %>

app/views/businesses/index.html.erb
<div class="album text-muted">
<div class="container">
  <div class="row">
    <% if @businesses.any? %>
      <% @businesses.find_each do |business| %>
        <div class="yp-card">
          <%= image_tag business.image.url, style: 'height: 280px; width: 100%; display: block;' %>

          <h1 class="lead">
            <%= link_to business_path(business) do %>
              <%= business.name %>
            <% end %>
          </h1>
          <p class="yp-card-text"><%= business.description %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/businesses/new.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-yp">
  <div class="container">
    <h1 class="display-3">Add a Business</h1>
    <p class="lead">Add General Description, Coupon, Services/Products and much more</p>
  </div>
</div>
<div class="container-rw">
  <div class="card">
  <div class="card-block">
  </div>
  <!-- <img class="card-img-top" src="" alt="Card image cap"> -->
  <%= render 'form' %>
</div>
</div>

app/views/businesses/show.html.erb
<div class="container">
  <h4><%= @business.name %></h1>
  <%= image_tag @business.image.url, style: 'height: 280px; width: 300px; display: block;' %>

</div>

app/views/layouts/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="pull-xs-right">
      <a href="#">Back to top</a>
    </p>
    <p>Yp is © Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
  </div>
</footer>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to 'Edit Account', edit_user_registration_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'nav-link' %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Join', new_user_registration_path, class: 'nav-link' %>
  </li>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-light">
  <%= link_to "yp", root_path, class: 'navbar-brand' %>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <%= link_to businesses_path, class: 'nav-link' do %>
        Find businesses <span class="sr-only">(current)</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to "Advertise With Us", new_business_path, class: 'nav-link'%> 
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Help</a>
    </li>
    <ul class="nav navbar-nav pull-xs-right">
      <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "layouts/navbar" -%>
  <%= yield %>
  <%= render "layouts/footer" -%>
</body>
</html>

app/views/pages/home.html.erb
    <section class="jumbotron text-xs-center jumbotron-yp">
      <div class="container">
        <h1 class="jumbotron-heading">Sit back, relax, enjoy...</h1>
        <p class="lead text-muted">YP will keep all of your business contact info up-to-date and current, automatically</p>
        <p>
          <a href="#" class="btn btn-yp">Main call to action</a>
          <a href="#" class="btn btn-secondary">Secondary action</a>
        </p>
      </div>
    </section>

    <div class="album text-muted">
      <div class="container">

        <div class="row">
          <div class="yp-card">
            <img data-src="holder.js/100px280/thumb" alt="100%x280" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22356%22%20height%3D%22280%22%20viewBox%3D%220%200%20356%20280%22%20preserveAspectRatio%3D%22none%22%3E%3C!--%0ASource%20URL%3A%20holder.js%2F100px280%2Fthumb%0ACreated%20with%20Holder.js%202.8.2.%0ALearn%20more%20at%20http%3A%2F%2Fholderjs.com%0A(c)%202012-2015%20Ivan%20Malopinsky%20-%20http%3A%2F%2Fimsky.co%0A--%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%3C!%5BCDATA%5B%23holder_1539bb8b566%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A18pt%20%7D%20%5D%5D%3E%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1539bb8b566%22%3E%3Crect%20width%3D%22356%22%20height%3D%22280%22%20fill%3D%22%23EEEEEE%22%2F%3E%3Cg%3E%3Ctext%20x%3D%22131.2890625%22%20y%3D%22148.1%22%3E356x280%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
            <p class="yp-card-text">This is a wider yp-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="yp-card">
            <img data-src="holder.js/100px280/thumb" alt="100%x280" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22356%22%20height%3D%22280%22%20viewBox%3D%220%200%20356%20280%22%20preserveAspectRatio%3D%22none%22%3E%3C!--%0ASource%20URL%3A%20holder.js%2F100px280%2Fthumb%0ACreated%20with%20Holder.js%202.8.2.%0ALearn%20more%20at%20http%3A%2F%2Fholderjs.com%0A(c)%202012-2015%20Ivan%20Malopinsky%20-%20http%3A%2F%2Fimsky.co%0A--%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%3C!%5BCDATA%5B%23holder_1539bb91b87%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A18pt%20%7D%20%5D%5D%3E%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1539bb91b87%22%3E%3Crect%20width%3D%22356%22%20height%3D%22280%22%20fill%3D%22%23EEEEEE%22%2F%3E%3Cg%3E%3Ctext%20x%3D%22131.2890625%22%20y%3D%22148.1%22%3E356x280%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
            <p class="yp-card-text">This is a wider yp-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="yp-card">
            <img data-src="holder.js/100px280/thumb" alt="100%x280" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22356%22%20height%3D%22280%22%20viewBox%3D%220%200%20356%20280%22%20preserveAspectRatio%3D%22none%22%3E%3C!--%0ASource%20URL%3A%20holder.js%2F100px280%2Fthumb%0ACreated%20with%20Holder.js%202.8.2.%0ALearn%20more%20at%20http%3A%2F%2Fholderjs.com%0A(c)%202012-2015%20Ivan%20Malopinsky%20-%20http%3A%2F%2Fimsky.co%0A--%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%3C!%5BCDATA%5B%23holder_1539bb8dafb%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A18pt%20%7D%20%5D%5D%3E%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1539bb8dafb%22%3E%3Crect%20width%3D%22356%22%20height%3D%22280%22%20fill%3D%22%23EEEEEE%22%2F%3E%3Cg%3E%3Ctext%20x%3D%22131.2890625%22%20y%3D%22148.1%22%3E356x280%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
            <p class="yp-card-text">This is a wider yp-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>

          <div class="yp-card">
            <img data-src="holder.js/100px280/thumb" alt="100%x280" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22356%22%20height%3D%22280%22%20viewBox%3D%220%200%20356%20280%22%20preserveAspectRatio%3D%22none%22%3E%3C!--%0ASource%20URL%3A%20holder.js%2F100px280%2Fthumb%0ACreated%20with%20Holder.js%202.8.2.%0ALearn%20more%20at%20http%3A%2F%2Fholderjs.com%0A(c)%202012-2015%20Ivan%20Malopinsky%20-%20http%3A%2F%2Fimsky.co%0A--%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%3C!%5BCDATA%5B%23holder_1539bb8c6fa%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A18pt%20%7D%20%5D%5D%3E%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1539bb8c6fa%22%3E%3Crect%20width%3D%22356%22%20height%3D%22280%22%20fill%3D%22%23EEEEEE%22%2F%3E%3Cg%3E%3Ctext%20x%3D%22131.2890625%22%20y%3D%22148.1%22%3E356x280%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
            <p class="yp-card-text">This is a wider yp-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="yp-card">
            <img data-src="holder.js/100px280/thumb" alt="100%x280" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22356%22%20height%3D%22280%22%20viewBox%3D%220%200%20356%20280%22%20preserveAspectRatio%3D%22none%22%3E%3C!--%0ASource%20URL%3A%20holder.js%2F100px280%2Fthumb%0ACreated%20with%20Holder.js%202.8.2.%0ALearn%20more%20at%20http%3A%2F%2Fholderjs.com%0A(c)%202012-2015%20Ivan%20Malopinsky%20-%20http%3A%2F%2Fimsky.co%0A--%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%3C!%5BCDATA%5B%23holder_1539bb90076%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A18pt%20%7D%20%5D%5D%3E%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1539bb90076%22%3E%3Crect%20width%3D%22356%22%20height%3D%22280%22%20fill%3D%22%23EEEEEE%22%2F%3E%3Cg%3E%3Ctext%20x%3D%22131.2890625%22%20y%3D%22148.1%22%3E356x280%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
            <p class="yp-card-text">This is a wider yp-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
          <div class="yp-card">
            <img data-src="holder.js/100px280/thumb" alt="100%x280" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22356%22%20height%3D%22280%22%20viewBox%3D%220%200%20356%20280%22%20preserveAspectRatio%3D%22none%22%3E%3C!--%0ASource%20URL%3A%20holder.js%2F100px280%2Fthumb%0ACreated%20with%20Holder.js%202.8.2.%0ALearn%20more%20at%20http%3A%2F%2Fholderjs.com%0A(c)%202012-2015%20Ivan%20Malopinsky%20-%20http%3A%2F%2Fimsky.co%0A--%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%3C!%5BCDATA%5B%23holder_1539bb91da6%20text%20%7B%20fill%3A%23AAAAAA%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A18pt%20%7D%20%5D%5D%3E%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1539bb91da6%22%3E%3Crect%20width%3D%22356%22%20height%3D%22280%22%20fill%3D%22%23EEEEEE%22%2F%3E%3Cg%3E%3Ctext%20x%3D%22131.2890625%22%20y%3D%22148.1%22%3E356x280%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
            <p class="yp-card-text">This is a wider yp-card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>

      </div>
    </div>